# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**" # frontendに変更のあった時のみ実行

jobs:
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{secrets.VERCEL_TOKEN}}
                  vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
                  # working-directory: ./frontend
